### PR TITLE
Profile Page + Edit Profile Page

### PR DESCRIPTION
**Pull request by pigeonpal**
I made some changes to app.py, models.py, ftb_schema.sql, _template.html, profile.html, and profile_edit.html.
app.py saw changes to the three /profile routes.
models.py has a change in the User class, as well as two new tables, UserGames and GameTag.
ftb_schema.sql has a change in the Player table, and two new tables corresponding to those in models.py.
I made minimal changes to the _template.html file so a user's profile picture can populate on the right side of the NavBar.
profile.html and profile_edit.html were added to their own folder since I experimented with different .js files. Ultimately, they are the only two in this folder, but this decision seems inconsequential.
profile.html renders a user's profile page in the form of four cards. These separate the username/name/profile picture from the Game List, Bio Section, and Forum Posts.
profile_edit.html renders a similar user's page, but each changeable input has forms in order for these changes to be made.

### CODE REVIEW

**Review by weiraven — CHANGES_REQUESTED** [review]
- Unclear what the function of GameTag table and class is supposed to accomplish, as you have not been communicating with the group on your intentions for Profile features.
- Profile pics currently comes from a directory you added to our static folder which users should not have access to. pchang made an imgBB account and integrated it with our project, so please work with him on using existing features for end-users. I have also mentioned during several of our sprint meetings that we should not try to store image files on our native databases as we have limited space and this is an unsustainable model if we were to seriously carry this product forward.
- I made the change to store user_id in session upon login already which routes the profile to user_id when I added the profile link to the user dropdown menu so I'm not sure why you changed the render_template to use sessionUser=session['username'] instead?
- post route for /profile/edit is named 'player()' which is not descriptive of what function actually accomplishes. Please consider renaming as it is confusing to have a player function that is for editing the user's profile rather than anything to do with gameplay.
- User profile references the new table you've added for gametags and usergames but none of these actually reference or appear to have any association with the game sessions we've been building. Why aren't User's currently involved game sessions hosted by our web app referenced or displayed?
- GameTag class names seem to be set to UNIQUE implying there can only ever exist one gametag to reference a specific game, if that is intentionally, then Users should be offered a list to select from when choosing their gametags, otherwise users will only be able to enter gametags with unique names that no other user has chosen before.
- UserGames logic and GameTag class definition were also inserted above the User class definition in models.py which is a confusing organization/formatting choice...
- Navbar styling was removed from _template.html to style.css per tzimnick more than two weeks ago.
- You deleted the original profile.html file and created a whole new subdirectory just for profile.html and profile_edit.html. Firstly, to follow our naming conventions, "edit_profile.html" would have made more sense. Secondly, you did not edit the linking on forums where I had already built links from usernames to the profile page.. so now this feature is broken. Additionally, I simply don't think we need a whole extra folder for two files html files.

If you had had any communications with us or spoken up about any of the things you were intending during our many stand-ups, many of these issues/conflicts could have been clarified and/or avoided.

**Comment by pigeonpal** [comment]
To address your requested changes, I have made corresponding bullet points:

- GameTag is as we initially discussed in Sprint 0. A user is able to add games they play and are interested in to their profile. These games are sourced from the GameTag table, and if another user has added a game it will populate for every user.
- This can be changed easily. I will submit another pull request once I have this working.
- This was a recommendation from one of the TAs.
- Okay. I am not sure this is such a big deal. I have updated this.
- This is a different feature.
- Yes, this is so multiple users cannot enter “D&D” for example. That way the “D&D” entry can be applied to different profiles. Once games are entered into the database, users can select them.
- Per Flask documentation, the many to many relationship table must come before child tables… 
- This has already been updated.
- This change was explained in the original pull request. I have moved them back. It is a common convention to keep related files together, by giving them matching prefixes, so “profile” and “profile_edit” are found under the “p”s.

I was under the impression that the profile features were not only self-explanatory, but also were previously discussed at the beginning of the project. A lot of these concerns are unsubstantial and not critical issues/conflicts.

**Review by tzimnick — APPROVED** [review]
Looked over code changes and was shown demonstration, looks good!

**Review by weiraven — APPROVED** [review]
Approving because I don't have time to argue with code that's being submitted less than 48 hours before the whole project is due. It's faster for me to just fix and adjust around it at this point.

**Pull request merged**
