### PR TITLE
Working Profile Image Upload

### PR DESCRIPTION
**Pull request by pigeonpal**
Shoutout to Phillip for writing a great imgbb function!

This PR saw changes to app.py, profile.html, and _template.html, and the deletion of the temporary profile_pic static image folder.
- The changes to app.py involved updating the image-saving code.
- profile.html saw the source of the image change to imgbb instead of the local.
- _template.html had the same change as profile.html, for the mini profile picture.
- The profile_pic static folder was deleted.

### CODE REVIEW

**Review by ChaChang-Byte — CHANGES_REQUESTED** [review]
copy the code for upload, rename it something else and another url and route your code to it because it will interfere with my socket calling.

**Comment by pigeonpal** [comment]
I have switched to the current version of the function. Everything is working as expected.

**Review by ChaChang-Byte — APPROVED** [review]
lgtm doesn't call the socket anymore

**Review by weiraven — APPROVED** [review]
per PChang

**Pull request merged**
